# Generated by Django 4.2.10 on 2025-03-08 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="anthropic_api_key",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Anthropic API Key"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="openai_api_key",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="OpenAI API Key"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="preferred_ai_service",
            field=models.CharField(
                blank=True,
                choices=[("openai", "OpenAI"), ("anthropic", "Anthropic")],
                default="openai",
                max_length=20,
                verbose_name="Preferred AI Service",
            ),
        ),
    ]
