# Generated by Django 4.2.10 on 2025-04-11 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_anthropic_api_key_user_openai_api_key_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="anthropic_api_key",
        ),
        migrations.RemoveField(
            model_name="user",
            name="openai_api_key",
        ),
        migrations.RemoveField(
            model_name="user",
            name="preferred_ai_service",
        ),
    ]
