# Generated by Django 4.2.10 on 2025-04-22 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_remove_api_key_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="inactivity_timeout",
            field=models.IntegerField(
                default=1800,
                help_text="Time in seconds before automatic logout due to inactivity",
                verbose_name="Inactivity Timeout (seconds)",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="stay_logged_in",
            field=models.BooleanField(
                default=False,
                help_text="Whether to keep the user logged in across browser sessions",
                verbose_name="Stay Logged In",
            ),
        ),
    ]
