# Generated by Django 4.2.10 on 2025-04-28 10:11

from django.db import migrations, models
from django.utils.translation import gettext_lazy as _


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_inactivity_timeout_user_stay_logged_in'),
    ]

    operations = [
        # First add the field if it doesn't exist
        migrations.AddField(
            model_name='user',
            name='subscription_tier',
            field=models.CharField(
                choices=[('explorer', 'Explorer'), ('creator', 'Creator'), ('master', 'Master')],
                default='explorer',
                max_length=50,
                verbose_name='Subscription Tier'
            ),
            preserve_default=True,
        ),
        # Then remove it
        migrations.RemoveField(
            model_name='user',
            name='subscription_tier',
        ),
    ]
