# Generated by Django 4.2.10 on 2025-04-28 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_subscription_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Stripe Customer ID'),
        ),
        migrations.AddField(
            model_name='organization',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Stripe Subscription ID'),
        ),
        migrations.AddField(
            model_name='organization',
            name='subscription_status',
            field=models.CharField(default='active', max_length=50, verbose_name='Subscription Status'),
        ),
        migrations.AddField(
            model_name='organization',
            name='subscription_period_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Subscription Period End'),
        ),
        migrations.AddField(
            model_name='organization',
            name='ai_generations_used',
            field=models.IntegerField(default=0, verbose_name='AI Generations Used This Month'),
        ),
        migrations.AddField(
            model_name='organization',
            name='ai_generations_reset_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='AI Generations Reset Date'),
        ),
    ]
