# Generated by Django 4.2.10 on 2025-04-29 08:08
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_add_stripe_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='cancel_at_period_end',
            field=models.BooleanField(default=False, verbose_name='Cancel At Period End'),
        ),
    ]
