# Generated by Django 4.2.10 on 2025-04-30 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_add_cancel_at_period_end_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_verification_token",
            field=models.CharField(
                blank=True,
                help_text="Token used for email verification",
                max_length=100,
                null=True,
                verbose_name="Email Verification Token",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="subscription_plan",
            field=models.CharField(
                choices=[
                    ("explorer", "Explorer"),
                    ("creator", "Creator"),
                    ("master", "Master"),
                ],
                default="explorer",
                max_length=50,
                verbose_name="Subscription Plan",
            ),
        ),
    ]
