# Generated by Django 4.2.10 on 2025-05-05 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_alter_user_email_unique"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="bonus_ai_generation_credits",
            field=models.IntegerField(
                default=0,
                help_text="Additional one-time AI generation credits that reset monthly",
                verbose_name="Bonus AI Generation Credits",
            ),
        ),
    ]
