# Generated by Django 4.2.10 on 2025-05-06 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_add_bonus_ai_generation_credits"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="marketing_consent",
            field=models.BooleanField(
                default=False,
                help_text="Whether the user has consented to receiving marketing emails",
                verbose_name="Marketing Email Consent",
            ),
        ),
    ]
