# Generated by Django 4.2.23 on 2025-08-07 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_user_marketing_consent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organization",
            name="ai_generations_reset_date",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="ai_generations_used",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="cancel_at_period_end",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="stripe_subscription_id",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="subscription_period_end",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="subscription_plan",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="subscription_status",
        ),
        migrations.AddField(
            model_name="organization",
            name="ai_credits_balance",
            field=models.IntegerField(
                default=0,
                help_text="Purchased credits that don't expire",
                verbose_name="AI Credits Balance",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="ai_credits_purchased_total",
            field=models.IntegerField(
                default=0,
                help_text="Lifetime total of credits purchased for tracking",
                verbose_name="Total AI Credits Purchased",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="bonus_ai_generation_credits",
            field=models.IntegerField(
                default=0,
                help_text="Free bonus credits given by admin (don't expire)",
                verbose_name="Bonus AI Generation Credits",
            ),
        ),
    ]
