# Generated by Django 4.2.23 on 2025-08-07 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_remove_organization_ai_generations_reset_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CreditPackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Package Name")),
                (
                    "display_name",
                    models.CharField(max_length=100, verbose_name="Display Name"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                ("credits", models.IntegerField(verbose_name="Credits Included")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Price"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="USD", max_length=3, verbose_name="Currency"
                    ),
                ),
                (
                    "stripe_price_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Stripe Price ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
            ],
            options={
                "verbose_name": "Credit Package",
                "verbose_name_plural": "Credit Packages",
                "ordering": ["price"],
            },
        ),
        migrations.CreateModel(
            name="CreditPurchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "credits_purchased",
                    models.IntegerField(verbose_name="Credits Purchased"),
                ),
                (
                    "amount_paid",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Amount Paid"
                    ),
                ),
                (
                    "stripe_payment_intent_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Stripe Payment Intent ID",
                    ),
                ),
                (
                    "purchase_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Purchase Date"
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credit_purchases",
                        to="accounts.organization",
                        verbose_name="Organization",
                    ),
                ),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchases",
                        to="accounts.creditpackage",
                        verbose_name="Package",
                    ),
                ),
            ],
            options={
                "verbose_name": "Credit Purchase",
                "verbose_name_plural": "Credit Purchases",
                "ordering": ["-purchase_date"],
            },
        ),
    ]
