# Generated by Django 4.2.23 on 2025-08-07 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_creditpackage_creditpurchase"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="google_id",
            field=models.CharField(
                blank=True,
                help_text="Google's unique identifier for OAuth authentication",
                max_length=100,
                null=True,
                unique=True,
                verbose_name="Google ID",
            ),
        ),
    ]
