# Generated by Django 4.2.7 on 2025-04-28 09:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_user_inactivity_timeout_user_stay_logged_in'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Plan Name')),
                ('stripe_price_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Stripe Price ID')),
                ('display_name', models.CharField(max_length=100, verbose_name='Display Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='Currency')),
                ('interval', models.CharField(choices=[('month', 'Monthly'), ('year', 'Yearly')], default='month', max_length=20, verbose_name='Billing Interval')),
                ('ai_generation_limit', models.IntegerField(default=0, verbose_name='AI Generation Limit')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Subscription Plan',
                'verbose_name_plural': 'Subscription Plans',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('subscription_created', 'Subscription Created'), ('subscription_updated', 'Subscription Updated'), ('subscription_cancelled', 'Subscription Cancelled'), ('payment_succeeded', 'Payment Succeeded'), ('payment_failed', 'Payment Failed'), ('trial_started', 'Trial Started'), ('trial_ended', 'Trial Ended')], max_length=50, verbose_name='Event Type')),
                ('stripe_event_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Stripe Event ID')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='Event Data')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_events', to='accounts.organization', verbose_name='Organization')),
            ],
            options={
                'verbose_name': 'Subscription Event',
                'verbose_name_plural': 'Subscription Events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIGenerationUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='First day of the month', verbose_name='Month')),
                ('count', models.IntegerField(default=0, verbose_name='Generation Count')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_generation_usage', to='accounts.organization', verbose_name='Organization')),
            ],
            options={
                'verbose_name': 'AI Generation Usage',
                'verbose_name_plural': 'AI Generation Usage',
                'ordering': ['-month'],
                'unique_together': {('organization', 'month')},
            },
        ),
    ]
