# Generated by Django 4.2.7 on 2025-04-28 09:56

from django.db import migrations


def create_default_subscription_plans(apps, schema_editor):
    """
    Create the default subscription plans.
    """
    SubscriptionPlan = apps.get_model('subscriptions', 'SubscriptionPlan')
    
    # Define the default subscription plans
    plans = [
        {
            'name': 'explorer',
            'display_name': 'Explorer',
            'description': 'Free plan with limited AI generation (3 per month)',
            'price': 0.00,
            'currency': 'USD',
            'interval': 'month',
            'ai_generation_limit': 3,
            'is_active': True,
        },
        {
            'name': 'creator',
            'display_name': 'Creator',
            'description': 'Standard plan with 100 AI generations per month',
            'price': 9.00,
            'currency': 'USD',
            'interval': 'month',
            'ai_generation_limit': 100,
            'is_active': True,
        },
        {
            'name': 'master',
            'display_name': 'Master',
            'description': 'Premium plan with 500 AI generations per month',
            'price': 19.00,
            'currency': 'USD',
            'interval': 'month',
            'ai_generation_limit': 500,
            'is_active': True,
        },
    ]
    
    # Create each plan
    for plan_data in plans:
        SubscriptionPlan.objects.create(**plan_data)


def remove_default_subscription_plans(apps, schema_editor):
    """
    Remove the default subscription plans.
    """
    SubscriptionPlan = apps.get_model('subscriptions', 'SubscriptionPlan')
    SubscriptionPlan.objects.filter(name__in=['explorer', 'creator', 'master']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_subscription_plans, remove_default_subscription_plans),
    ]
