# Generated by Django 4.2.10 on 2025-04-29 08:40
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_add_subscription_cancellation_error_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionevent',
            name='event_type',
            field=models.CharField(
                choices=[
                    ('subscription_created', 'Subscription Created'),
                    ('subscription_updated', 'Subscription Updated'),
                    ('subscription_cancelled', 'Subscription Cancelled'),
                    ('subscription_cancelled_by_upgrade', 'Subscription Cancelled By Upgrade'),
                    ('subscription_cancelled_by_downgrade', 'Subscription Cancelled By Downgrade'),
                    ('subscription_cancellation_error', 'Subscription Cancellation Error'),
                    ('payment_succeeded', 'Payment Succeeded'),
                    ('payment_failed', 'Payment Failed'),
                    ('trial_started', 'Trial Started'),
                    ('trial_ended', 'Trial Ended'),
                ],
                max_length=50,
                verbose_name='Event Type'
            ),
        ),
    ]
