# Generated by Django 4.2.23 on 2025-08-13 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_user_google_id"),
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="category",
            unique_together={("organization", "name")},
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, verbose_name="Slug"),
        ),
        migrations.AlterUniqueTogether(
            name="category",
            unique_together={("organization", "name"), ("organization", "slug")},
        ),
    ]
