# Generated by Django 4.2.10 on 2025-03-09 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0003_documentpdfexport"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentpdfexport",
            name="expiration_type",
            field=models.CharField(
                choices=[
                    ("1h", "1 Hour"),
                    ("24h", "24 Hours"),
                    ("1w", "1 Week"),
                    ("1m", "1 Month"),
                    ("never", "Never"),
                ],
                default="1w",
                max_length=10,
                verbose_name="Expiration Type",
            ),
        ),
        migrations.AddField(
            model_name="documentpdfexport",
            name="pin_code",
            field=models.CharField(
                blank=True, max_length=4, null=True, verbose_name="PIN Code"
            ),
        ),
        migrations.AddField(
            model_name="documentpdfexport",
            name="pin_protected",
            field=models.BooleanField(default=False, verbose_name="PIN Protected"),
        ),
    ]
