# Generated by Django 4.2.10 on 2025-03-10 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0004_documentpdfexport_expiration_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="textdocument",
            name="content",
            field=models.TextField(
                default="", help_text="Markdown content", verbose_name="Content"
            ),
        ),
    ]
