# Generated by Django 4.2.10 on 2025-03-26 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_anthropic_api_key_user_openai_api_key_and_more"),
        ("documents", "0005_alter_textdocument_content"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIPromptTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("system_message", "System Message"),
                            ("new_content", "New Content Generation"),
                            ("summary", "Summary Generation"),
                            ("analysis", "Analysis Generation"),
                            ("comparison", "Comparison Generation"),
                            ("custom", "Custom Document Generation"),
                            ("formatting", "Formatting Instructions"),
                        ],
                        max_length=20,
                        verbose_name="Template Type",
                    ),
                ),
                ("content", models.TextField(verbose_name="Content")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="If set, this template will only be used for this organization. Leave blank for global templates.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_templates",
                        to="accounts.organization",
                        verbose_name="Organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Prompt Template",
                "verbose_name_plural": "AI Prompt Templates",
                "ordering": ["template_type", "name"],
                "unique_together": {("template_type", "organization")},
            },
        ),
    ]
