# Generated by Django 4.2.10 on 2025-04-15 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0012_add_very_short_document_template"),
    ]

    operations = [
        migrations.AddField(
            model_name="aimodelsettings",
            name="is_default",
            field=models.BooleanField(
                default=False,
                help_text="If checked, this model will be used as the default",
                verbose_name="Is Default",
            ),
        ),
        migrations.AddField(
            model_name="aimodelsettings",
            name="temperature",
            field=models.FloatField(
                default=0.7,
                help_text="Controls randomness: 0.0 is deterministic, 1.0+ is very creative",
                verbose_name="Temperature",
            ),
        ),
    ]
