# Generated by Django 4.2.10 on 2025-04-15 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0013_add_temperature_and_default_to_ai_model_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="aimodelsettings",
            name="analysis_temperature",
            field=models.FloatField(
                default=0.7,
                help_text="Controls randomness for style analysis: 0.0 is deterministic, 1.0+ is very creative",
                verbose_name="Analysis Temperature",
            ),
        ),
        migrations.AlterField(
            model_name="aimodelsettings",
            name="temperature",
            field=models.FloatField(
                default=0.7,
                help_text="Controls randomness for document generation: 0.0 is deterministic, 1.0+ is very creative",
                verbose_name="Generation Temperature",
            ),
        ),
    ]
