# Generated by Django 4.2.10 on 2025-04-15 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0014_add_analysis_temperature_to_ai_model_settings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aiprompttemplate",
            name="template_type",
            field=models.CharField(
                choices=[
                    ("system_message", "System Message"),
                    ("new_content", "New Content Generation"),
                    ("summary", "Summary Generation"),
                    ("analysis", "Analysis Generation"),
                    ("comparison", "Comparison Generation"),
                    ("custom", "Custom Document Generation"),
                    ("formatting", "Formatting Instructions"),
                    ("style_analysis", "Style Analysis"),
                ],
                max_length=20,
                verbose_name="Template Type",
            ),
        ),
    ]
