# Generated by Django 4.2.10 on 2025-04-15 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_remove_api_key_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("documents", "0015_add_style_analysis_template_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aiprompttemplate",
            name="template_type",
            field=models.CharField(
                choices=[
                    ("system_message", "System Message"),
                    ("new_content", "New Content Generation"),
                    ("summary", "Summary Generation"),
                    ("analysis", "Analysis Generation"),
                    ("comparison", "Comparison Generation"),
                    ("custom", "Custom Document Generation"),
                    ("formatting", "Formatting Instructions"),
                    ("style_analysis", "Style Analysis"),
                    ("style_condensation", "Style Condensation"),
                ],
                max_length=20,
                verbose_name="Template Type",
            ),
        ),
        migrations.CreateModel(
            name="StyleConstraint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "constraints",
                    models.JSONField(default=dict, verbose_name="Style Constraints"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_style_constraints",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="If set, this style constraint will only be used for this organization. Leave blank for global constraints.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="style_constraints",
                        to="accounts.organization",
                        verbose_name="Organization",
                    ),
                ),
                (
                    "reference_documents",
                    models.ManyToManyField(
                        blank=True,
                        related_name="referenced_in_style_constraints",
                        to="documents.textdocument",
                        verbose_name="Reference Documents",
                    ),
                ),
            ],
            options={
                "verbose_name": "Style Constraint",
                "verbose_name_plural": "Style Constraints",
                "ordering": ["-created_at"],
            },
        ),
    ]
