# Generated by Django 4.2.23 on 2025-08-06 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0016_add_style_constraint_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentpdfexport",
            name="share_url",
            field=models.URLField(blank=True, max_length=500, verbose_name="Share URL"),
        ),
    ]
