# Generated by Django 4.2.23 on 2025-08-11 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0017_documentpdfexport_share_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="textdocument",
            name="is_demo",
            field=models.BooleanField(
                default=False,
                help_text="Whether this document is demo content for new users",
                verbose_name="Is Demo Content",
            ),
        ),
    ]
