# Generated by Django 4.2.23 on 2025-08-21 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0018_textdocument_is_demo"),
    ]

    operations = [
        migrations.AddField(
            model_name="textdocument",
            name="demo_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
