# Generated by Django 4.2.10 on 2025-05-05 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SystemMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Optional title for the message",
                        max_length=200,
                        null=True,
                    ),
                ),
                ("message", models.TextField(help_text="The content of the message")),
                (
                    "location",
                    models.CharField(
                        choices=[
                            ("dashboard", "Dashboard"),
                            ("subscription", "Subscription"),
                            ("register", "Register"),
                        ],
                        help_text="Where this message should be displayed",
                        max_length=50,
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("info", "Information"),
                            ("warning", "Warning"),
                            ("success", "Success"),
                            ("error", "Error"),
                        ],
                        default="info",
                        help_text="The type of message (affects styling)",
                        max_length=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this message is currently active",
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Optional start date for when this message should be displayed",
                        null=True,
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Optional end date for when this message should stop being displayed",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "System Message",
                "verbose_name_plural": "System Messages",
                "ordering": ["-created_at"],
            },
        ),
    ]
