# Generated by Django 4.2.10 on 2025-05-05 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system_messages", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemmessage",
            name="disable_functionality",
            field=models.BooleanField(
                default=False,
                help_text="Whether to disable the functionality of the page (e.g., disable registration form)",
            ),
        ),
    ]
